version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"   
      - "5001:5001" 
    volumes:
      - ./data/dot-net-webapp:/home/dot-net-webapp
      # - ~/.aspnet/https:/https:ro
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_TRACE_DEBUG=true
      - DD_LOGS_INJECTION=true  # Enable the connectiong of APM traces with Logs
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      #- ASPNETCORE_URLS=https://+;http://+
      #- ASPNETCORE_HTTPS_PORT=5001
      #- ASPNETCORE_HTTP_PORT=5000
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=password
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    labels:
      com.datadoghq.ad.logs: '[{"source": "csharp", "service": "csharp"}]'
    depends_on:
      - datadog-agent
    networks:
      - poc

  datadog-agent:
    image: datadog/agent:latest
    #env_file:
    #  - ~/sandbox.docker.env    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      # - ./logs:/var/log/datadog/
    #ports:
    #  - 127.0.0.1:8126:8126/tcp
    environment:
      - DD_SITE=datadoghq.com # AWS East (us1=datadoghq.com), AZ West (us3=us3.datadoghq.com), GCP US West (us5=us5.datadoghq.com), GCP EU (eu1=eu1.datadoghq.com)
      - DD_API_KEY=${DD_API_KEY} # Datadog API Key, set it as '- DD_APY_KEY=${DD_API_KEY}' to get val from env 'export DD_API_KEY=<DD-API-KEY>'
      - DD_ENV=sandbox  # Name of the current environment (sandbox, qa, uat, prod, etc)
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true # Statsd to Dogstatsd metrics
      - DD_TRACE_SAMPLE_RATE=1 # 1 = 100% traces collected
      - DD_APM_ENABLED=true # Enable APM tracing
      - DD_APM_NON_LOCAL_TRAFFIC=true # Enable/include tracing from other containers
      - DD_SYSTEM_PROBE_ENABLED=true  # Enable Network Perf collection from system probe, additional settings required for cap_add (may not be compatible with MacOS)
      - DD_PROCESS_AGENT_ENABLED=true # Enable collection of container app/processes 
      - DD_LOGS_ENABLED=true  # Enable log collection 
      - DD_LOG_LEVEL=INFO # Change the agent log level to DEBUG for troubleshooting purposes
      - DD_LOGS_INJECTION=true  # Enable trace_id, span_id APM correlation injection into logs
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true # All Logs are collected for container via stderr/stdout
      - DD_LOGS_DIRECT_SUBMISSION_INTEGRATIONS=Serilog  # Enable direct submission of logs to DD, options are: Serilog, ILogger, Log4Net, NLog
      - DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE=true   # Enable container file logs collection with the use of labels 'com.datadoghq.ad.logs'
      - DD_RUNTIME_SECURITY_CONFIG_ENABLED=true # Enable collection of container security audit
      - DD_AC_EXCLUDE=name:datadog-agent
    networks:
      - poc



networks:
  poc:
    driver: bridge